### PR TITLE
Solved issue Check if player move is valid or not #4

### PR DESCRIPTION
**Pull request by kaushikatgithub**
In the Game class's play() method, I added functionality to locate chess pieces using standard chess notation, such as 'D4' or 'E3'. I then added a condition to check for valid moves and perform a move.

To validate a move, I implemented a function called is_valid_move() for all the piece classes and the ChessBoard class. Each piece has predefined move patterns, so I checked those patterns to validate the moves.

For the king-castle move, I implemented two functions. The first checks whether the current move is a king-castle. If it is, the rook's position is updated within the is_valid_move() method, and the king is moved like any other piece. I assumed that when a player wants to castle, they must provide the castled location of the king as the end position. For example, to perform a white kingside castle, the start location would be E1, and the end location would be G1.

To track whether the king or rook has moved, I added an attribute called is_untouched, which is initially set to True.

Screenshot 2024-10-03 171941

### CODE REVIEW

**Comment by kaushikatgithub** [comment]
hey, i have refined a code for is_diagonal_move() method of class Bishop and Queen.

CODE:
`# Placeholder for validating diagonal movement
    def is_diagonal_move(self, start, end):
        
        start_x, start_y = start
        end_x, end_y = end

        # Check for valid diagonal move usign the condition: (x, y) where |x-i| = |y-j|
        is_dia_move = (abs(start_x - end_x) == abs(start_y - end_y))
        return is_dia_move`

**Comment by kaushikatgithub** [comment]
Also i wanted to make some changed for castling, like create separate method to perform castling.

**Comment by VrundDA** [comment]
I have viewed your commits it has some errors, which I will display and resolve these issues. 
This pull request is closed.
Error_4

**Comment by kaushikatgithub** [comment]
As i mentioned comment above, i resolved this issue by updating the diagonal movement logic for Bishop and Queen class. Please consider that.

**Comment by kaushikatgithub** [comment]
Is it accepted or not? If yes can you tell me when will it be merged i want to work on another issue.

**Comment by desairudra** [comment]
Still we are gettin the same error,we have decided to merging this pull request.And we will be creating a new issue related to the error and assigning it to you for resolution.

**Pull request merged**
